spring:
  datasource:
    url: jdbc:h2:mem:popzii;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 4000

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
